# creating the app-1 service
apiVersion: v1
kind: Service
metadata:
  name: app-2-svc
spec:
  selector:
    app: app-2 # selects the pod "app-2"
  ports:
    - protocol: TCP
      port: 8080 # reroutes traffice from 8080 to 3000
      targetPort: 3000