# creating the nginx configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data: # defining the nginx configuration file
  default.conf: |
    upstream backend {
        server app-1:8080;
        server app-2:8080;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }
